[package]
name = "rue"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["display"] }
expect-test = "1.5.1"
indexmap = "2.10.0"
num-derive = "0.4.2"
num-traits = "0.2.19"
rowan = "0.16.1"
thiserror = "2.0.12"
