name: Build
on:
  push:
    branches:
      - main
    tags:
      - "**"

  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --all-features --workspace

      - name: Clippy
        run: cargo clippy --workspace --all-features --all-targets

      - name: Unused dependencies
        run: |
          cargo install cargo-machete --locked
          cargo machete

      - name: Fmt
        run: cargo fmt --all -- --files-with-diff --check

      - name: Publish
        if: startsWith(github.event.ref, 'refs/tags')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --workspace
